/*
-- Query: SELECT * FROM capstone_form.registration
LIMIT 0, 1000

-- Date: 2020-04-06 21:54
*/
USE capstone_form;
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('e01','Proj E01 - BlackBox','software',NULL,NULL,3,3,NULL,0,NULL,NULL,64,81,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('e02','Proj E02 - Do-Do','1:1 prototype',NULL,NULL,2,2,NULL,0,NULL,NULL,59,86,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('e03','Proj E03 - FlexiHome','1:1 prototype',NULL,NULL,3.5,3.5,NULL,0,NULL,NULL,70,88,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('f29','Proj F29 - inlingua_Management System','software',NULL,NULL,0.5,0.5,NULL,0,NULL,NULL,62,83,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('f37','Proj F37 - MITRE_Air Traffic Control','1:1 prototype',NULL,NULL,4,3,NULL,0,NULL,NULL,57,74,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p01','Proj 01 - Attila_Cyber Security','1:1 prototype',NULL,NULL,2,2,NULL,0,NULL,NULL,66,76,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p07','Proj 07 - BCA_Creative and Interactive Communication Platform','1:1 prototype',NULL,NULL,2.5,2.5,NULL,0,NULL,NULL,64,88,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p10','Proj 10 - BCA_Reengineering with Robotics','1:1 prototype',NULL,NULL,3,3,NULL,0,NULL,NULL,71,76,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p11','Proj 11 - Bordeaux_Water Condensation','1:1 prototype',NULL,NULL,3,3,NULL,0,NULL,NULL,57,91,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p12','Proj 12 - Centurion_Traffic Flow and Storage of Bicycles','1:1 prototype',NULL,NULL,2,2,NULL,0,NULL,NULL,57,81,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p13','Proj 13 - Centurion_Smart Mini-Mart','1:1 prototype',NULL,NULL,2,2,NULL,0,NULL,NULL,71,83,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p14','Proj 14 - Citibank_Commercial Banking Relationships','software',NULL,NULL,2,3,NULL,0,NULL,NULL,52,93,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p15','Proj 15 - CPG_Urban Metabolic Hub','1:1 prototype',NULL,NULL,4,2,NULL,0,NULL,NULL,66,71,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p16','Proj 16 - Dassault_Virtual Twin','1:1 prototype',NULL,NULL,2,2,NULL,0,NULL,NULL,54,86,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p17','Proj 17 - DP Architects_Assisted Bathing Solution','1:1 prototype',NULL,NULL,6,8,NULL,0,NULL,NULL,78,76,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p20','Proj 20 - Esplanade_Empowered Patron','1:1 prototype',NULL,NULL,1.5,1.5,NULL,0,NULL,NULL,53,82,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p21','Proj 21 - Flex_Smart Safety Access Auditor','1:1 prototype',NULL,NULL,3,3,NULL,0,NULL,NULL,57,67,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p22','Proj 22 - Force 21_Birloki System','1:1 prototype',NULL,NULL,4,2,NULL,0,NULL,NULL,75,67,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p24','Proj 24 - Heinz_People Analytics','software',NULL,NULL,2,1,NULL,0,NULL,NULL,52,79,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p25','Proj 25 - HopeTechnik_Embedded Robotic Officer','1:1 prototype',NULL,NULL,3,5,NULL,0,NULL,NULL,46,82,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p26','Proj 26 - HopeTechnik_Robotic Detector','1:1 prototype',NULL,NULL,2.5,2.5,NULL,0,NULL,NULL,64,94,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p33','Proj 33 - LTA_Cyclist User Alert','1:1 prototype',NULL,NULL,3,3,NULL,0,NULL,NULL,78,93,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p34','Proj 34 - LTA_Drain Covers','1:1 prototype',NULL,NULL,2,2,NULL,0,NULL,NULL,51,68,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p35','Proj 35 - Metta School_Interpersonal Space Awareness','software',NULL,NULL,5,3,NULL,0,NULL,NULL,64,64,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p38','Proj 38 - MKPL_Innovative Furniture','1:1 prototype',NULL,NULL,4,4,NULL,0,NULL,NULL,82,100,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p39','Proj 39 - MSD_Personalized Drug Design','1:1 prototype',NULL,NULL,2,2,NULL,0,NULL,NULL,73,96,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p40','Proj 40 - MXHL_Machine Learning Algorithms','software',NULL,NULL,1,1,NULL,0,NULL,NULL,50,76,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p41','Proj 41 - NUS_Pediatric Surgery Neural Network','software',NULL,NULL,2,2,NULL,0,NULL,NULL,47,94,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p43','Proj 43 - PA_POP-UPHood','1:1 prototype',NULL,NULL,2,2,NULL,0,NULL,NULL,46,71,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p46','Proj 46 - RollsRoyce_Energy Harvesting Wireless Sensor','1:1 prototype',NULL,NULL,2,1,NULL,0,NULL,NULL,48,65,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p47','Proj 47 - RollsRoyce_Spare Parts Onboard Ships','1:1 prototype',NULL,NULL,3.5,3.5,NULL,0,NULL,NULL,84,60,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p49','Proj 49 - Sembcorp_Small Weight Delivery','1:1 prototype',NULL,NULL,3,2,NULL,0,NULL,NULL,50,100,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p50','Proj 50 - SIA_All-Weather Working Shelter','1:1 prototype',NULL,NULL,2.5,2,NULL,0,NULL,NULL,53,62,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p51','Proj 51 - SIA_Premium Passenger Experience','1:1 prototype',NULL,NULL,2.5,1,NULL,0,NULL,NULL,75,64,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p53','Proj 53 - S-Lineage_Breathing Tower','1:1 prototype',NULL,NULL,3,3,NULL,0,NULL,NULL,84,68,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p54','Proj 54 - Sree Narayana_Improving Living Environment','1:1 prototype',NULL,NULL,4,4,NULL,0,NULL,NULL,41,104,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p55','Proj 55 - Sree Narayana_Redesign Residential Facility','1:1 prototype',NULL,NULL,2,2,NULL,0,NULL,NULL,45,77,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p61','Proj 61 - Steelcase_Reduction of Logistics and Packaging Costs','software',NULL,NULL,3,2,NULL,0,NULL,NULL,43,60,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p62','Proj 62 - TataComm_App Performance Management','software',NULL,NULL,2,2,NULL,0,NULL,NULL,59,62,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p63','Proj 63 - TataComm_SmartChat','software',NULL,NULL,1,0.5,NULL,0,NULL,NULL,54,91,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p65','Proj 65 - TVConal_Cricket Broadcast','software',NULL,NULL,0.5,0.5,NULL,0,NULL,NULL,62,81,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p68','Proj 68 - Weijenberg_Smart Generative Furniture Design','1:1 prototype',NULL,NULL,5,6,NULL,0,NULL,NULL,27,51,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p69','Proj 69 - CGH_Drip Detection Device','1:1 prototype',NULL,NULL,0.5,0.5,NULL,0,NULL,NULL,55,77,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p70','Proj 70 - CGH_Patient Transfer Device','1:1 prototype',NULL,NULL,4,4,NULL,0,NULL,NULL,37,84,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p71','Proj 71 - ASTAR_Pediatric Robotic Pet','1:1 prototype',NULL,NULL,2,2,NULL,0,NULL,NULL,43,66,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('p72','Proj 72 - ASTAR_Human Behaviour','software',NULL,NULL,2,1.5,NULL,0,NULL,NULL,64,60,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('s01','Proj S01 - 2359 Media_Percy','software',NULL,NULL,2,2,NULL,0,NULL,NULL,85,93,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('s02','Proj S02 - DSO_Synthetic Aperture Radar','1:1 prototype',NULL,NULL,10,3,NULL,0,NULL,NULL,-1,-1,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('s03','Proj S03 - GIC_Skynet','software',NULL,NULL,0.5,0.5,NULL,0,NULL,NULL,64,72,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('s04','Proj S04 - NHB_Printing Light','1:1 prototype',NULL,NULL,11.5,7,NULL,0,NULL,NULL,-1,-1,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('s05','Proj S05 - Performance Rotors_AEOLUS','1:1 prototype',NULL,NULL,3,3,NULL,0,NULL,NULL,69,57,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('s06','Proj S06 - RGA_Mixed Reality Redefines Education','1:1 prototype',NULL,NULL,2,3,NULL,0,NULL,NULL,40,97,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('s07','Proj S07 - Shado EV_BLDC Design','1:1 prototype',NULL,NULL,5,5,NULL,0,NULL,NULL,22,88,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('s08','Proj S08 - SMRT_ABTUS','1:1 prototype',NULL,NULL,3,3,NULL,0,NULL,NULL,38,77,1);
INSERT INTO registration (`id`,`groupName`,`prototype`,`category`,`company`,`width`,`height`,`sizeNweight`,`powerpoints`,`pedestal`,`otherRequest`,`posX`,`posY`,`level`) VALUES ('s09','Proj S09 - Weijenberg_Reinforced Wood Tower','1:1 prototype',NULL,NULL,2,2,NULL,0,NULL,NULL,76,59,1);
